export const placeholder = {
    'title': "Dr",
    'email': "name@example.com",
    'expertise': "Chemical Engineering",
    'category': "Engineering",
    'phone_no': "+44 08844 734551",
    'education': "(E.g.) Current - Past  1. Bachelor 1988/09 – 1992/07 china Peking University Mechanical Engineering",
    'employment': "(E.g. ) Current - Past  1. Principal Reseracher 20/14/09-20/17/12 USA General Electric Company",
    'projects': "1. 20/18/01-20/19/03 | Development of manganese-based lithiumion batteries and supercapacitors (funded by DST/NRF) |$1000,0000 | 25 | R & D Manager and Principal Investigator ",
    'patents': "(E.g. ) Current - Past  1. Date Filling (2018) | Publication Number(#98120393) | Patent Title (General Electric Cooker) | Organization (Company C) | Assignee (Company C Chairman)",
    'field_of_speciality': "Field of Specialty (Main research areas, Previous research results, Industry and international influence)：",
    'awards': "Awards and Honours", 
    'products': "Product introduction, current industrialization level and industry competitiveness）",
    'publication_date': "(E.g. ) Current - Past 2014, ADVANCES IN ENGINEERING RESEARCH, Volume 8, chapter 2, Adsorption Refrigeration, Victoria M. Petrova Editor. Nova Publishers. New York, Ahmed Rezk, Ahmed Elsayed, Saad Mahmoud, and Raya AL-Dadah.",
    'recent_major_research_projects': "(E.g. ) Current - Past Project briefs, innovations compared to existing technologies, current developments and technical difficulties, expected results and industry, and international influence",
    'collaborative_project_proposal': "Project Proposal With China",

    'job_title': "Accountant Manager",
    'employer': "Amazon",
    'area': "United Kingdom",
    'salary': "35,000 - 45,000",
    'featured': "Amazon Advertising operates at the intersection of advertising and ecommerce and offers advertisers a rich array of innovative advertising solutions across Amazon’s mobile and desktop websites, proprietary devices and the Amazon Advertising Platform.",
    'job_description': "In this role you will be working within the SME team of Account Managers, taking ownership of the management of a portfolio of SME clients and engaging with to ensure renewals and upsells.",
    'required_expertise': "Management, Data, SQL",
    'responsibilities': " -Onboarding and engagement process with every client.   -Identify risks to minimise attrition.   -Identify and convert opportunities to up sell and cross sell existing products.   -Create and convert cross sell opportunities.   -Establish and maintain relationship with key client stakeholders. ",
    'essential_skills': "-Commercially and client focused   -Sales and relationship management experience   -Experience working to commercial KPI’s"
}